name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: paysfr

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/paysfr/paysfer-ingram-cdf-service-repo/paysfer-ingram-cdf-service:latest .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/paysfr/paysfer-ingram-cdf-service-repo/paysfer-ingram-cdf-service:latest

      - name: Deploy to Cloud Run
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_ARTIFACT_REGION: ${{ secrets.GCP_ARTIFACT_REGION }}
          GCP_RUN_REGION: ${{ secrets.GCP_RUN_REGION }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          PORT: ${{ secrets.PORT }}
        run: |
          gcloud run deploy paysfer-ingram-cdf-service \
            --image=${GCP_ARTIFACT_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/paysfer-ingram-cdf-service-repo/paysfer-ingram-cdf-service:latest \
            --region=${GCP_RUN_REGION} \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars=FTP_HOST=${FTP_HOST},FTP_PORT=${FTP_PORT},FTP_USER=${FTP_USER},FTP_PASSWORD=${FTP_PASSWORD}
